from django.contrib import admin

from .models import AppUser, Currency, Account, Transaction, MonthlyBudget
from .consts import (
    MODEL_USER_ID_APP_USER,
    MODEL_USER_NAME,
    MODEL_USER_LASTNAME,
    MODEL_USER_EMAIL,
    MODEL_CURRENCY_ID_CURRENCY,
    MODEL_CURRENCY_NAME,
    MODEL_CURRENCT_SHORT_NAME,
    MODEL_CURRENCY_TO_PLN,
    MODEL_ACCOUNT_ID_ACCOUNT,
    MODEL_ACCOUNT_ID_APP_USER,
    MODEL_ACCOUNT_NAME,
    MODEL_ACCOUNT_BALANCE,
    MODEL_ACCOUNT_MAIN_CURRENCY,
    MODEL_ACCOUNT_START_TIME,
    MODEL_ACCOUNT_END_TIME,
    MODEL_TRANSACTION_ID_TRANSACTION,
    MODEL_TRANSACTION_ID_ACCOUNT,
    MODEL_TRANSACTION_AMOUNT,
    MODEL_TRANSACTION_CURRENCY,
    MODEL_TRANSACTION_TIME,
    MODEL_TRANSACTION_DESCRIPTION,
    MODEL_MONTHLY_BUDGET_ID_MONTHLY_BUDGET,
    MODEL_MONTHLY_BUDGET_ID_APP_USER,
    MODEL_MONTHLY_BUDGET_MONTH,
    MODEL_MONTHLY_BUDGET_MAIN_INCOME,
    MODEL_MONTHLY_BUDGET_SECONDARY_INCOME,
    MODEL_MONTHLY_BUDGET_GROCERIES,
    MODEL_MONTHLY_BUDGET_RENT,
    MODEL_MONTHLY_BUDGET_TRANSPORTATION,
    MODEL_MONTHLY_BUDGET_ENTERTAINMENT,
    MODEL_MONTHLY_BUDGET_DEBT,
    MODEL_MONTHLY_BUDGET_SUBSCRIPTIONS,
    MODEL_MONTHLY_BUDGET_SAVINGS,
    MODEL_MONTHLY_BUDGET_OTHER_SPENDINGS,
)

# Register your models here.


class AppUserAdmin(admin.ModelAdmin):
    readonly_fields = (MODEL_USER_ID_APP_USER,)
    list_display = (
        MODEL_USER_ID_APP_USER,
        MODEL_USER_NAME,
        MODEL_USER_LASTNAME,
        MODEL_USER_EMAIL,
    )


class CurrencyAdmin(admin.ModelAdmin):
    readonly_fields = (MODEL_CURRENCY_ID_CURRENCY,)
    list_display = (
        MODEL_CURRENCY_ID_CURRENCY,
        MODEL_CURRENCY_NAME,
        MODEL_CURRENCT_SHORT_NAME,
        MODEL_CURRENCY_TO_PLN,
    )


class AccountAdmin(admin.ModelAdmin):
    prepopulated_fields = {"slug": (MODEL_ACCOUNT_NAME,)}
    readonly_fields = (MODEL_ACCOUNT_ID_ACCOUNT,)
    list_display = (
        MODEL_ACCOUNT_ID_ACCOUNT,
        MODEL_ACCOUNT_ID_APP_USER,
        MODEL_ACCOUNT_NAME,
        MODEL_ACCOUNT_BALANCE,
        MODEL_ACCOUNT_MAIN_CURRENCY,
        MODEL_ACCOUNT_START_TIME,
        MODEL_ACCOUNT_END_TIME,
    )


class TransactionAdmin(admin.ModelAdmin):
    readonly_fields = (MODEL_TRANSACTION_ID_TRANSACTION,)
    list_display = (
        MODEL_TRANSACTION_ID_TRANSACTION,
        MODEL_TRANSACTION_ID_ACCOUNT,
        MODEL_TRANSACTION_AMOUNT,
        MODEL_TRANSACTION_CURRENCY,
        MODEL_TRANSACTION_TIME,
        MODEL_TRANSACTION_DESCRIPTION,
    )


class MonthlyBudgetAdmin(admin.ModelAdmin):
    readonly_fields = (MODEL_MONTHLY_BUDGET_ID_MONTHLY_BUDGET,)
    list_display = (
        MODEL_MONTHLY_BUDGET_ID_MONTHLY_BUDGET,
        MODEL_MONTHLY_BUDGET_ID_APP_USER,
        MODEL_MONTHLY_BUDGET_MONTH,
        MODEL_MONTHLY_BUDGET_MAIN_INCOME,
        MODEL_MONTHLY_BUDGET_SECONDARY_INCOME,
        MODEL_MONTHLY_BUDGET_GROCERIES,
        MODEL_MONTHLY_BUDGET_RENT,
        MODEL_MONTHLY_BUDGET_TRANSPORTATION,
        MODEL_MONTHLY_BUDGET_ENTERTAINMENT,
        MODEL_MONTHLY_BUDGET_DEBT,
        MODEL_MONTHLY_BUDGET_SUBSCRIPTIONS,
        MODEL_MONTHLY_BUDGET_SAVINGS,
        MODEL_MONTHLY_BUDGET_OTHER_SPENDINGS,
    )


admin.site.register(AppUser, AppUserAdmin)
admin.site.register(Currency, CurrencyAdmin)
admin.site.register(Account, AccountAdmin)
admin.site.register(Transaction, TransactionAdmin)
admin.site.register(MonthlyBudget, MonthlyBudgetAdmin)
