# models
MODEL_USER_NAME_MAX_LENGTH = 50
MODEL_USER_LAST_NAME_MAX_LENGTH = 50
MODEL_USER_EMAIL_MAX_LENGTH = 100

MODEL_CURRENCY_NAME_MAX_LENGTH = 20
MODEL_CURRENCY_SHORT_NAME_MAX_LENGTH = 3

MODEL_ACCOUNT_NAME_MAX_LENGTH = 50
MODEL_ACCOUNT_SLUG_MAX_LENGTH = 50

MODEL_TRANSACTION_DESCRIPTION_MAX_LENGTH = 100

MODEL_USER_ID_USER = "id_user"
MODEL_USER_NAME = "name"
MODEL_USER_LASTNAME = "lastname"
MODEL_USER_EMAIL = "email"

MODEL_CURRENCY_ID_CURRENCY = "id_currency"
MODEL_CURRENCY_NAME = "name"
MODEL_CURRENCT_SHORT_NAME = "short_name"
MODEL_CURRENCY_TO_PLN = "to_pln"

MODEL_ACCOUNT_ID_ACCOUNT = "id_account"
MODEL_ACCOUNT_ID_USER = "id_user"
MODEL_ACCOUNT_NAME = "name"
MODEL_ACCOUNT_BALANCE = "balance"
MODEL_ACCOUNT_MAIN_CURRENCY = "main_currency"
MODEL_ACCOUNT_START_TIME = "start_time"
MODEL_ACCOUNT_END_TIME = "end_time"
MODEL_ACCOUNT_SLUG = "slug"

MODEL_TRANSACTION_ID_TRANSACTION = "id_transaction"
MODEL_TRANSACTION_ID_ACCOUNT = "id_account"
MODEL_TRANSACTION_AMOUNT = "amount"
MODEL_TRANSACTION_CURRENCY = "currency"
MODEL_TRANSACTION_TIME = "time"
MODEL_TRANSACTION_DESCRIPTION = "description"


# views context
LANDING_PAGE_VIEW_CONTEXT_ACCOUNTS = "accounts"

BUDGET_MANAGER_VIEW_CONTEXT_TRANSACTIONS = "transactions"
BUDGET_MANAGER_VIEW_CONTEXT_FILTER_FORM = "filter_form"

# vies request
REQUEST_KEY_START_DATE = "start_date"
REQUEST_KET_END_DATE = "end_date"
REQUEST_KEY_TRANSACTION_TYPE = "transaction_type"

REQUEST_VALUE_CREDIT = "credit"
REQUEST_VALUE_DEBIT = "debit"

# templates
TEMPLATE_LANDING_PAGE = "budget_manager/landing_page.html"
TEMPLATE_BUDGET_DETAILS = "budget_manager/budget_details.html"
