# models
MODEL_USER_NAME_MAX_LENGTH = 50
MODEL_USER_LAST_NAME_MAX_LENGTH = 50

MODEL_CURRENCY_NAME_MAX_LENGTH = 20
MODEL_CURRENCY_SHORT_NAME_MAX_LENGTH = 3

MODEL_ACCOUNT_NAME_MAX_LENGTH = 50
MODEL_ACCOUNT_SLUG_MAX_LENGTH = 50

MODEL_TRANSACTION_DESCRIPTION_MAX_LENGTH = 100

MODEL_MONTHLY_BUDGET_MONTH_MAX_LENGTH = 10

MODEL_USER_ID_APP_USER = "id_app_user"
MODEL_USER_NAME = "name"
MODEL_USER_LASTNAME = "lastname"
MODEL_USER_EMAIL = "email"

MODEL_CURRENCY_ID_CURRENCY = "id_currency"
MODEL_CURRENCY_NAME = "name"
MODEL_CURRENCT_SHORT_NAME = "short_name"
MODEL_CURRENCY_TO_PLN = "to_pln"

MODEL_ACCOUNT_ID_ACCOUNT = "id_account"
MODEL_ACCOUNT_ID_USER = "id_user"
MODEL_ACCOUNT_NAME = "name"
MODEL_ACCOUNT_BALANCE = "balance"
MODEL_ACCOUNT_MAIN_CURRENCY = "main_currency"
MODEL_ACCOUNT_START_TIME = "start_time"
MODEL_ACCOUNT_END_TIME = "end_time"
MODEL_ACCOUNT_SLUG = "slug"

MODEL_TRANSACTION_ID_TRANSACTION = "id_transaction"
MODEL_TRANSACTION_ID_ACCOUNT = "id_account"
MODEL_TRANSACTION_AMOUNT = "amount"
MODEL_TRANSACTION_CURRENCY = "currency"
MODEL_TRANSACTION_TIME = "time"
MODEL_TRANSACTION_DESCRIPTION = "description"

MODEL_MONTHLY_BUDGET_ID_MONTHLY_BUDGET = "id_monthly_budget"
MODEL_MONTHLY_BUDGET_ID_USER = "id_user"
MODEL_MONTHLY_BUDGET_MONTH = "month"
MODEL_MONTHLY_BUDGET_MAIN_INCOME = "main_income"
MODEL_MONTHLY_BUDGET_SECONDARY_INCOME = "secondary_income"
MODEL_MONTHLY_BUDGET_GROCERIES = "groceries"
MODEL_MONTHLY_BUDGET_RENT = "rent"
MODEL_MONTHLY_BUDGET_TRANSPORTATION = "transportation"
MODEL_MONTHLY_BUDGET_ENTERTAINMENT = "entertainment"
MODEL_MONTHLY_BUDGET_DEBT = "debt"
MODEL_MONTHLY_BUDGET_SUBSCRIPTIONS = "subscriptions"
MODEL_MONTHLY_BUDGET_SAVINGS = "savings"
MODEL_MONTHLY_BUDGET_OTHER_SPENDINGS = "other_spendings"

# views context
LANDING_PAGE_VIEW_CONTEXT_ACCOUNTS = "accounts"

BUDGET_MANAGER_VIEW_CONTEXT_TRANSACTIONS = "transactions"
BUDGET_MANAGER_VIEW_CONTEXT_FILTER_FORM = "filter_form"

# vies request
REQUEST_KEY_START_DATE = "start_date"
REQUEST_KET_END_DATE = "end_date"
REQUEST_KEY_TRANSACTION_TYPE = "transaction_type"

REQUEST_VALUE_CREDIT = "credit"
REQUEST_VALUE_DEBIT = "debit"

# templates
TEMPLATE_LANDING_PAGE = "budget_manager/landing_page.html"
TEMPLATE_BUDGET_DETAILS = "budget_manager/budget_details.html"
