# Generated by Django 5.0.4 on 2024-06-05 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                ("id_currency", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("short_name", models.CharField(max_length=3)),
                ("to_pln", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name_plural": "Currencies",
            },
        ),
        migrations.CreateModel(
            name="AppUser",
            fields=[
                ("id_app_user", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "App Users",
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id_account", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_time", models.DateField()),
                ("end_time", models.DateField(blank=True, null=True)),
                ("slug", models.SlugField()),
                (
                    "id_app_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budget_manager.appuser",
                    ),
                ),
                (
                    "main_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budget_manager.currency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MonthlyBudget",
            fields=[
                (
                    "id_monthly_budget",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("month", models.CharField(max_length=10)),
                ("main_income", models.PositiveIntegerField(default=0, null=True)),
                ("secondary_income", models.PositiveIntegerField(default=0, null=True)),
                ("groceries", models.PositiveIntegerField(default=0, null=True)),
                ("rent", models.PositiveIntegerField(default=0, null=True)),
                ("transportation", models.PositiveIntegerField(default=0, null=True)),
                ("entertainment", models.PositiveIntegerField(default=0, null=True)),
                ("debt", models.PositiveIntegerField(default=0, null=True)),
                ("subscriptions", models.PositiveIntegerField(default=0, null=True)),
                ("savings", models.PositiveIntegerField(default=0, null=True)),
                ("other_spendings", models.PositiveIntegerField(default=0, null=True)),
                (
                    "id_app_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budget_manager.appuser",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Monthly Budgets",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id_transaction", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("time", models.DateTimeField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budget_manager.currency",
                    ),
                ),
                (
                    "id_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budget_manager.account",
                    ),
                ),
            ],
        ),
    ]
