# Generated by Django 5.0.3 on 2024-04-29 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id_currency', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('short_name', models.CharField(max_length=3)),
                ('to_pln', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id_account', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('balance', models.FloatField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_manager.currency')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_manager.user')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id_transaction', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('time', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_manager.currency')),
                ('id_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_manager.account')),
            ],
        ),
    ]
