# Generated by Django 5.0.3 on 2024-05-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
