# Generated by Django 5.0.3 on 2024-05-02 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_manager', '0002_alter_account_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id_monthly_budget', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=10)),
                ('main_income', models.IntegerField(default=0, null=True)),
                ('secondary_income', models.IntegerField(default=0, null=True)),
                ('groceries', models.IntegerField(default=0, null=True)),
                ('rent', models.IntegerField(default=0, null=True)),
                ('transportation', models.IntegerField(default=0, null=True)),
                ('entertainment', models.IntegerField(default=0, null=True)),
                ('debt', models.IntegerField(default=0, null=True)),
                ('subscriptions', models.IntegerField(default=0, null=True)),
                ('savings', models.IntegerField(default=0, null=True)),
                ('other_spendings', models.IntegerField(default=0, null=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_manager.appuser')),
            ],
        ),
    ]
