# Generated by Django 5.0.3 on 2024-05-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_manager', '0003_monthlybudget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybudget',
            name='debt',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='entertainment',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='groceries',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='main_income',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='other_spendings',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='rent',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='savings',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='secondary_income',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='subscriptions',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='transportation',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
