# Generated by Django 5.0.3 on 2024-04-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_manager', '0003_alter_account_id_account_alter_currency_id_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterField(
            model_name='account',
            name='end_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='start_time',
            field=models.DateField(),
        ),
    ]
