# Generated by Django 5.0.3 on 2024-04-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_manager', '0004_alter_currency_options_alter_account_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
