# Generated by Django 5.0.4 on 2024-04-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget_manager", "0005_alter_account_end_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="balance",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="currency",
            name="to_pln",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
