# Generated by Django 5.0.3 on 2024-05-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_manager', '0006_alter_account_balance_alter_currency_to_pln_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='slug',
            field=models.SlugField(default='test-acc'),
        ),
    ]
