# Generated by Django 5.0.3 on 2024-05-02 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_manager', '0006_alter_account_id_app_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybudget',
            name='id_app_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budget_manager.appuser'),
        ),
    ]
